-- Load the .NET SDK-style .csproj generator
local dotnet = dofile("premake/dotnet.lua")

-- Define the C# project (this generates the .csproj when premake runs)
local scriptCore = dotnet.project("Timefall-ScriptCore")
scriptCore.location = "Timefall-ScriptCore"
scriptCore.targetFramework = "net9.0"
scriptCore.kind = "library"
scriptCore.allowUnsafeBlocks = true
scriptCore.nullable = "enable"
scriptCore.implicitUsings = "enable"
scriptCore.rootNamespace = "Timefall"
-- Auto-copy outputs to the editor resources folder
scriptCore.copyOutputTo = {
    "$(MSBuildThisFileDirectory)../Timefall-Editor/Resources/Scripts"
}

workspace "Timefall"
    architecture "x86_64" -- This applies to native C++ projects only
	startproject "Timefall-Editor"

	configurations
	{
		"Debug",
		"Release",
		"Dist"
	}

	multiprocessorcompile "On"

outputdir = "%{cfg.buildcfg}-%{cfg.system}-%{cfg.architecture}"

-- Include directories relative to Timefall folder (Timefall project directory)
IncludeDir = {}
IncludeDir["GLFW"] = "vendor/GLFW/include"
IncludeDir["Glad"] = "vendor/Glad/include"
IncludeDir["filewatch"] = "vendor/filewatch"
IncludeDir["ImGui"] = "vendor/imgui"
IncludeDir["glm"] = "vendor/glm"
IncludeDir["stb_image"] = "vendor/stb_image"
IncludeDir["entt"] = "vendor/entt/include"
IncludeDir["yaml_cpp"] = "vendor/yaml-cpp/include"
IncludeDir["ImGuizmo"] = "vendor/ImGuizmo"
IncludeDir["box2d"] = "vendor/box2d/include"
IncludeDir["hostfxr"] = "vendor/hostfxr/include"

-- Library directories relative to Timefall folder (Timefall project directory)
LibraryDir = {}
LibraryDir["hostfxr"] = "vendor/hostfxr/lib/%{cfg.buildcfg}"

group "Dependencies"
	include "Timefall/vendor/GLFW"
	include "Timefall/vendor/Glad"
	include "Timefall/vendor/imgui"
	include "Timefall/vendor/yaml-cpp"
	include "Timefall/vendor/box2d"

group ""

group "Core"
	include "Timefall"
	-- Reference the generated .csproj (generated by dotnet module above)
	externalproject "Timefall-ScriptCore"
		location "Timefall-ScriptCore"
		kind "SharedLib"
		language "C#"

group ""

group "Tools"
	include "Timefall-Editor"
group ""

group "Misc"
	include "Sandbox"
group ""